### PR TITLE
Add STV test/service buttons.

### PR DESCRIPTION
**Pull request by Tatsuya79**

### CODE REVIEW

**Comment by barbudreadmon** [comment]
A core option to disable those by default would be welcome (as i did in reicast), pressing service button by mistake while playing can be infuriating.

**Comment by Tatsuya79** [comment]
It's in.

**Comment by barbudreadmon** [comment]
Thanks :)

**Comment by barbudreadmon** [comment]
> Perhaps we need a bios selector option. (or the region detection failing?)

@Tatsuya79 We are already asking the right bios (US in this case)
https://github.com/libretro-mirrors/Kronos/blob/87dada3ae993c60e810b4248cc3008c1c91a1869/yabause/src/stv.c#L341

However, i think it's loading another bios for some reason, could you try standalone to see if you encounter the same issue ? (i can't test myself right now)

**Pull request merged**
