### PR TITLE
Add analog triggers for 3D pad.

### PR DESCRIPTION
**Pull request by Tatsuya79**
Analog triggers support.

I kept the right analog axis I added at first before I managed to add the trigger.
Can be useful later for twin sticks, who knows...

### CODE REVIEW

**Comment by fr500** [comment]
So you're implementing Analog buttons for L2/R2 right?
But then the descriptors are set for analog stick X/Y on the right stick.

Where are these inputs implemented originally (I mean in the physical pad), What buttons on the physical 3d pad would trigger the analog response?

**Comment by barbudreadmon** [comment]
About twin stick games, as mentioned in https://segaretro.org/Mission_Stick , it seems Panzer Dragoon Zwei was the only game with a dual analog stick setup. https://segaretro.org/Saturn_Twin-Stick was actually dual digital.

**Comment by Tatsuya79** [comment]
You can remap the triggers to the right stick but it uses the digital fallback then I guess.

**Comment by fr500** [comment]
I haven't tried your patch yet, but without it on Win 10 with an Xbox360 controller in Sega Rally Plus the car is always accelerating.

Is that correct?

**Comment by Tatsuya79** [comment]
No it shouldn't accelerate if nothing is touched.  
I don't think I had that problem before adding the triggers, but I could have forgotten.

**Pull request merged**
